In [4]:
# Code for Question 4C

import numpy as np

matrices = [np.random.randint(-10, 11, size=(3, 3)) for _ in range(3)]

for i, A in enumerate(matrices, start=1):
    print(f"\nMatrix A{i}:")
    print(A)

    try:
        A_inv = np.linalg.inv(A)
        print(f"\nInverse of A{i}:")
        print(A_inv)

        print(f"Product:")
        print(np.round(A @ A_inv, 6))

    except np.linalg.LinAlgError:
        print(f"\nMatrix A{i} is not invertible.")


Matrix A1:
[[ 8 -2  3]
 [-9  5 -1]
 [ 7  6  3]]

Inverse of A1:
[[-0.15107914 -0.17266187  0.09352518]
 [-0.14388489 -0.02158273  0.13669065]
 [ 0.64028777  0.44604317 -0.15827338]]
Product:
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]

Matrix A2:
[[-9  7  4]
 [-7  7 -6]
 [-8 -9 10]]

Inverse of A2:
[[ 0.01381693 -0.09153713 -0.06044905]
 [ 0.10189983 -0.05008636 -0.07081174]
 [ 0.10276339 -0.11830743 -0.01208981]]
Product:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A3:
[[ -6   5  -1]
 [-10 -10  -5]
 [ -8  -6  -1]]

Inverse of A3:
[[-0.06896552  0.03793103 -0.12068966]
 [ 0.10344828 -0.00689655 -0.06896552]
 [-0.06896552 -0.26206897  0.37931034]]
Product:
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [7]:
# Setup for Problem-5
import pandas as pd

df = pd.read_csv("kc_house_data.csv")
df = df.drop(columns=["id", "date", "zipcode"])

# Separating both variables
y = df["price"]
X = df.drop(columns=["price"])

In [8]:
statistics = pd.DataFrame({
    "mean": X.mean(),
    "min": X.min(),
    "max": X.max(),
    "variance": X.var(),
})
print(statistics)

                       mean        min           max      variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    47.1559  4.777760e+01  1.919990

In [12]:
lowest_avg = statistics["variance"].idxmin(), statistics["variance"].min()
highest_avg = statistics["variance"].idxmax(), statistics["variance"].max()

print("Lowest average:", lowest_avg)
print("Highest average:", highest_avg)

Lowest average: ('waterfront', np.float64(0.007485225502686407))
Highest average: ('sqft_lot', np.float64(1715658774.1754704))


In [16]:
correlations = X.corrwith(y).sort_values(ascending=False)

corr_table = pd.DataFrame({
    "Feature": correlations.index,
    "Correlation with Price": correlations.values
})

print(corr_table)

          Feature  Correlation with Price
0     sqft_living                0.702035
1           grade                0.667434
2      sqft_above                0.605567
3   sqft_living15                0.585379
4       bathrooms                0.525138
5            view                0.397293
6   sqft_basement                0.323816
7        bedrooms                0.308350
8             lat                0.307003
9      waterfront                0.266369
10         floors                0.256794
11   yr_renovated                0.126434
12       sqft_lot                0.089661
13     sqft_lot15                0.082447
14       yr_built                0.054012
15      condition                0.036362
16           long                0.021626
