In [4]:
# Code for Question 4C

import numpy as np

matrices = [np.random.randint(-10, 11, size=(3, 3)) for _ in range(3)]

for i, A in enumerate(matrices, start=1):
    print(f"\nMatrix A{i}:")
    print(A)

    try:
        A_inv = np.linalg.inv(A)
        print(f"\nInverse of A{i}:")
        print(A_inv)

        print(f"Product:")
        print(np.round(A @ A_inv, 6))

    except np.linalg.LinAlgError:
        print(f"\nMatrix A{i} is not invertible.")


Matrix A1:
[[ 8 -2  3]
 [-9  5 -1]
 [ 7  6  3]]

Inverse of A1:
[[-0.15107914 -0.17266187  0.09352518]
 [-0.14388489 -0.02158273  0.13669065]
 [ 0.64028777  0.44604317 -0.15827338]]
Product:
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]

Matrix A2:
[[-9  7  4]
 [-7  7 -6]
 [-8 -9 10]]

Inverse of A2:
[[ 0.01381693 -0.09153713 -0.06044905]
 [ 0.10189983 -0.05008636 -0.07081174]
 [ 0.10276339 -0.11830743 -0.01208981]]
Product:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A3:
[[ -6   5  -1]
 [-10 -10  -5]
 [ -8  -6  -1]]

Inverse of A3:
[[-0.06896552  0.03793103 -0.12068966]
 [ 0.10344828 -0.00689655 -0.06896552]
 [-0.06896552 -0.26206897  0.37931034]]
Product:
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
